import 'package:flutter/material.dart';

class EventTMColors {
  static const lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF36618E),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFB9CEE6),
    onPrimaryContainer: Color(0xFF132333),
    secondary: Color(0xFF535F70),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFD3DBE6),
    onSecondaryContainer: Color(0xFF262B33),
    tertiary: Color(0xFF6B5778),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFDED2E6),
    onTertiaryContainer: Color(0xFF2D2533),
    error: Color(0xFFBA1A1A),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFE6A7A7),
    onErrorContainer: Color(0xFF330707),
    surface: Color(0xFFfcfcfc),
    onSurface: Color(0xFF313233),
    surfaceContainerHighest: Color(0xFFdde1e6),
    onSurfaceVariant: Color(0xFF595f66),
    outline: Color(0xFF868f99),
  );

  static const darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFA6C5E6),
    onPrimary: Color(0xFF1D344C),
    primaryContainer: Color(0xFF274566),
    onPrimaryContainer: Color(0xFFB9CEE6),
    secondary: Color(0xFFCBD6E6),
    onSecondary: Color(0xFF39414C),
    secondaryContainer: Color(0xFF4B5766),
    onSecondaryContainer: Color(0xFFD3DBE6),
    tertiary: Color(0xFFDACAE6),
    onTertiary: Color(0xFF44384C),
    tertiaryContainer: Color(0xFF5B4A66),
    onTertiaryContainer: Color(0xFFDED2E6),
    error: Color(0xFFE68D8D),
    onError: Color(0xFF4C0B0B),
    errorContainer: Color(0xFF660E0E),
    onErrorContainer: Color(0xFFE6A7A7),
    surface: Color(0xFF313233),
    onSurface: Color(0xFFe3e4e6),
    surfaceContainerHighest: Color(0xFF595f66),
    onSurfaceVariant: Color(0xFFd9dfe6),
    outline: Color(0xFFa5abb3),
  );
}
